services:
  postgres:
    image: postgres:17
    container_name: patient_service_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: patient_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      target: builder # Stop at build stage, don't create runtime image
    ports:
      - "4000:4000"
    volumes:
      - ./src:/app/src # Mount source for hot reload
      - ./pom.xml:/app/pom.xml
      - maven_cache:/root/.m2 # Cache Maven dependencies
    command: ./mvnw spring-boot:run -Dspring-boot.run.jvmArguments="-Dspring.devtools.restart.enabled=true -Dspring.devtools.livereload.enabled=true" # Enable Spring Boot DevTools
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_LIVERELOAD_ENABLED=true
      - SPRING_DEVTOOLS_RESTART_POLL_INTERVAL=1000
      - SPRING_DEVTOOLS_RESTART_QUIET_PERIOD=400
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  postgres_data:
  maven_cache:
