services:
  postgres:
    image: postgres:17
    container_name: patient_service_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: patient_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: patient-service:latest
    build:
      context: .
    ports:
      - "4000:4000"
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  postgres_data:
